### ISSUE TITLE
Get the correct fclk0 frequency in set.fdrive

### ISSUE THREAD

**Issue by jacklovell** [petermilne/BOLODSP#16]
At the moment set.fdrive is hard-coded with the fclk0 (clk_AXI) frequency, and requires modifying depending on the version of the FSBL used in the system.

It's possible to get the actual frequency of the clock from Linux: http://www.wiki.xilinx.com/Controlling+FCLKs+in+Linux. set.fdrive should use this method to retrieve the fclk frequency instead.

**Comment by petermilne** [comment]
Recommend steering clear of the very complex and hard to understand Linux clock system. The info you'd want directly available here:
acq2106_132> cat /dev/acq400.0.knobs/axi_freq
125

So, sure easy add to set.fdrive  FCLK=$(cat  /dev/acq400.0.knobs/axi_freq)0000

But there's no point. ALL BOLOs are on ACQ2106. If there is anyone still trying to use BOLO with an ancient 100MHz FSBL, they have bigger problems than this, and they'd be well advised to get the FSBL upgraded. There are no known instances of ACQ2106+BOLO at 100MHz in the wild, and if they were then the most appropriate response would be:

if  [ $(cat /dev/acq400.0.knobs/axi_freq) != 125 ] ; then echo CALL D-TACQ;panic; fi
