### ISSUE TITLE
Option to disable writing offset RAM values for voltage

### ISSUE THREAD

**Issue by jacklovell** [petermilne/BOLODSP#17]
When `calibfit` produces a poor fit with incorrect offsets, loading these onto the FPGA produces confusing MAG and PHASE data. The offset correction is only necessary for the POW signal, so it would be useful to have a switch to disable writing the voltage offsets to the FPGA during the `run_calibfit` process.

Note that the power offsets are required to be correctly set if the POW signal is to be useful. No offsets == incorrect offsets == junk data, so disabling the writing of the power offset values isn't as useful.

Of course, ideally `calibfit` would be smart enough to know if its offsets are junk, or robust enough to not produce junk offsets unless it receives truly junk data. But getting this right will take a while, so a useful interim solution is needed.

**Comment by petermilne** [comment]
Implemented by option in /mnt/local/sysconfig/bolo.sh

commit d1a7830489586609b506238647faa7e48fc3dffb (HEAD -> master)
Author: Peter Milne <peter.milne@d-tacq.com>
Date:   Mon Jan 13 17:14:23 2020 +0000

    LOAD_POWER_FILTERS=1  : default, load power filters after calibration.
    LOAD_POWER_FILTERS=0  : do not load the power filters ie do not act on calibration
     On branch master
            modified:   usr/local/bin/run_calibfit

Now, if the filter calcs have been done remotely, HOW do we load them?

Maybe we should have "filter load as a service" ?
